### ISSUE TITLE
TASK - API ROUTES (under src/app/api)

### ISSUE THREAD

**Issue by BulaCooola** [BulaCooola/TourneyPro#7]

**Comment by BulaCooola** [comment]
api routes

/
> /register $\rightarrow$ Endpoint to register new users

> /user $\rightarrow$ Endpoint for authenticated user 
>> /user/[id] $\rightarrow$ Endpoint for authenticated user page
>> /user/settings $\rightarrow$ Endpoint for editing user page

> /users $\rightarrow$ Endpoint to get all users

> /teams $\rightarrow$ Endpoint to get all teams

> /team
>> /team/create $\rightarrow$ Endpoint to create a team
>> /teams/[id] $\rightarrow$ Endpoint to get one team
>> /team/[id]/members $\rightarrow$ Endpoint to add/remove members
>> /team/[id]/edit $\rightarrow$ Endpoint for editing team info 

>/tournament
>> /tournament/create $\rightarrow$ Endpoint to create the tournament
>> /tournament/[id] $\rightarrow$ Endpoint to view a tournament

> /search $\rightarrow$ Endpoint to search for teams/users/tournaments (like Lab 6 search Extra Credit)

**Comment by Padraig-Phelps** [comment]
done
